CREATE TABLE restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seed_key VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    address VARCHAR(300) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    catalog_source VARCHAR(2000) NOT NULL,
    catalog_verified_at DATE NOT NULL,
    estimated_check_per_guest NUMERIC(10, 2),
    check_estimation_type VARCHAR(9),
    check_source VARCHAR(2000),
    check_verified_at DATE,
    hours_source VARCHAR(2000),
    hours_verified_at DATE,
    CONSTRAINT uq_restaurants_seed_key UNIQUE (seed_key),
    CONSTRAINT ck_restaurant_identity CHECK (
        TRIM(seed_key) <> '' AND TRIM(name) <> '' AND TRIM(address) <> '' AND TRIM(catalog_source) <> ''),
    CONSTRAINT ck_restaurant_check CHECK (
        (estimated_check_per_guest IS NULL AND check_estimation_type IS NULL
            AND check_source IS NULL AND check_verified_at IS NULL)
        OR (estimated_check_per_guest IS NOT NULL AND estimated_check_per_guest > 0
            AND check_estimation_type IS NOT NULL AND check_estimation_type IN ('PUBLISHED', 'DERIVED')
            AND check_source IS NOT NULL AND TRIM(check_source) <> '' AND check_verified_at IS NOT NULL)),
    CONSTRAINT ck_restaurant_hours_metadata CHECK (
        (hours_source IS NULL AND hours_verified_at IS NULL)
        OR (hours_source IS NOT NULL AND TRIM(hours_source) <> '' AND hours_verified_at IS NOT NULL))
);

CREATE TABLE restaurant_cuisines (
    restaurant_id BIGINT NOT NULL REFERENCES restaurants(id),
    cuisine VARCHAR(20) NOT NULL,
    PRIMARY KEY (restaurant_id, cuisine),
    CONSTRAINT ck_cuisine CHECK (cuisine IN ('BELARUSIAN', 'ITALIAN', 'GEORGIAN'))
);

CREATE TABLE restaurant_tags (
    restaurant_id BIGINT NOT NULL REFERENCES restaurants(id),
    tag VARCHAR(20) NOT NULL,
    PRIMARY KEY (restaurant_id, tag),
    CONSTRAINT ck_tag CHECK (tag IN ('COZY', 'QUIET', 'ROMANTIC', 'CASUAL', 'FRIENDS', 'PREMIUM'))
);

CREATE TABLE opening_intervals (
    restaurant_id BIGINT NOT NULL REFERENCES restaurants(id),
    weekday VARCHAR(9) NOT NULL,
    opens_at TIME NOT NULL,
    closes_at TIME NOT NULL,
    closes_next_day BOOLEAN NOT NULL,
    PRIMARY KEY (restaurant_id, weekday, opens_at),
    CONSTRAINT ck_weekday CHECK (weekday IN (
        'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    CONSTRAINT ck_opening_interval CHECK (
        (NOT closes_next_day AND closes_at > opens_at)
        OR (closes_next_day AND closes_at < opens_at))
);
