ALTER TABLE restaurants ADD COLUMN menu_source VARCHAR(2000);
ALTER TABLE restaurants ADD COLUMN menu_verified_at DATE;
ALTER TABLE restaurants ADD COLUMN menu_coverage VARCHAR(7);
ALTER TABLE restaurants ADD CONSTRAINT ck_restaurant_menu_metadata CHECK (
    (menu_source IS NULL AND menu_verified_at IS NULL AND menu_coverage IS NULL)
    OR (menu_source IS NOT NULL AND TRIM(menu_source) <> '' AND menu_verified_at IS NOT NULL
        AND menu_coverage IS NOT NULL AND menu_coverage = 'PARTIAL'));

CREATE TABLE menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL REFERENCES restaurants(id),
    seed_key VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(5) NOT NULL,
    dish_type VARCHAR(5),
    price_byn NUMERIC(10,2) NOT NULL,
    portion VARCHAR(100),
    description VARCHAR(1000),
    source VARCHAR(2000),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_menu_item_seed_key UNIQUE (restaurant_id, seed_key),
    CONSTRAINT ck_menu_item_text CHECK (TRIM(seed_key) <> '' AND TRIM(name) <> ''
        AND (source IS NULL OR TRIM(source) <> '')
        AND (portion IS NULL OR TRIM(portion) <> '')
        AND (description IS NULL OR TRIM(description) <> '')),
    CONSTRAINT ck_menu_item_category CHECK (category IN ('MAIN', 'SOUP', 'PASTA')),
    CONSTRAINT ck_menu_item_dish_type CHECK (dish_type IS NULL OR (dish_type = 'PASTA' AND category = 'PASTA')),
    CONSTRAINT ck_menu_item_price CHECK (price_byn > 0)
);
-- The unique index begins with restaurant_id and also serves menu reads.
